name: Lint/Test/Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Lint/Test/Build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: NPM Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Check Types
        run: npm run check-types

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: ES Check
        run: npm run es-check
